// Phase 6 — P6-081
// ContentStatusGuard — defensive published-content-only filter.
//
// Purpose: Prevent unpublished curriculum content (draft, archived, or any
// other non-published status) from being rendered in the student app.
//
// Authority model:
// - The backend is the authority for content status. The datasource layer
//   already passes status=published as a query param (P6-077).
// - This guard is a defensive Flutter-side check that silently drops any
//   non-published items that may leak through (e.g. during a backend status
//   transition race, or if a future API change omits the filter).
// - Flutter NEVER computes or modifies status values — it only checks whether
//   the backend-supplied status string equals 'published'.
//
// Usage:
//   final safeAssets = ContentStatusGuard.filterAssets(allAssets);
//   final safeCourses = ContentStatusGuard.filterCourses(allCourses);
//   final safeChapters = ContentStatusGuard.filterChapters(allChapters);
//   final safeLessons = ContentStatusGuard.filterLessons(allLessons);
//   final isPublished = ContentStatusGuard.isPublished(item.status);

import 'package:aim_mobile/features/lessons/logic/entity/chapter.dart';
import 'package:aim_mobile/features/lessons/logic/entity/course.dart';
import 'package:aim_mobile/features/lessons/logic/entity/lesson.dart';
import 'package:aim_mobile/features/lessons/logic/entity/lesson_asset.dart';
import 'package:aim_mobile/features/lessons/logic/entity/level.dart';

/// Defensive published-content-only guard for the student mobile app.
///
/// All filtering is based on backend-supplied [status] strings only.
/// Flutter never assigns, computes, or infers status values.
class ContentStatusGuard {
  const ContentStatusGuard._();

  /// The only status value that is safe to render in the student app.
  static const String _published = 'published';

  /// Returns true if [status] is exactly 'published'.
  ///
  /// [status] is always a backend-supplied string; never generated by Flutter.
  static bool isPublished(String status) => status == _published;

  /// Filters a list of [Course] to include only published items.
  static List<T> filterCourses<T extends Course>(List<T> courses) =>
      courses.where((c) => isPublished(c.status)).toList();

  /// Filters a list of [Level] to include only published items.
  static List<T> filterLevels<T extends Level>(List<T> levels) =>
      levels.where((l) => isPublished(l.status)).toList();

  /// Filters a list of [Chapter] to include only published items.
  static List<T> filterChapters<T extends Chapter>(List<T> chapters) =>
      chapters.where((c) => isPublished(c.status)).toList();

  /// Filters a list of [Lesson] to include only published items.
  static List<T> filterLessons<T extends Lesson>(List<T> lessons) =>
      lessons.where((l) => isPublished(l.status)).toList();

  /// Filters a list of [LessonAsset] to include only published items.
  ///
  /// Note: the datasource (P6-077) already requests status=published; this
  /// guard is a second defensive layer.
  static List<T> filterAssets<T extends LessonAsset>(List<T> assets) =>
      assets.where((a) => isPublished(a.status)).toList();
}

