// Phase 6 — P6-081
// ContentStatusGuard — defensive published-content-only filter.
//
// Purpose: Prevent unpublished curriculum content (draft, archived, or any
// other non-published status) from being rendered in the student app.
//
// Authority model:
// - The backend is the authority for content status. The datasource layer
//   already passes status=published as a query param (P6-077).
// - This guard is a defensive Flutter-side check that silently drops any
//   non-published items that may leak through (e.g. during a backend status
//   transition race, or if a future API change omits the filter).
// - Flutter NEVER computes or modifies status values — it only checks whether
//   the backend-supplied status string equals 'published'.
//
// Usage:
//   final safeAssets = ContentStatusGuard.filterAssets(allAssets);
//   final safeCourses = ContentStatusGuard.filterCourses(allCourses);
//   final safeChapters = ContentStatusGuard.filterChapters(allChapters);
//   final safeLessons = ContentStatusGuard.filterLessons(allLessons);
//   final isPublished = ContentStatusGuard.isPublished(item.status);

import 'package:aim_mobile/features/lessons/data/models/lessons_models.dart';
import 'package:aim_mobile/features/lessons/logic/entity/lesson_asset.dart';

/// Defensive published-content-only guard for the student mobile app.
///
/// All filtering is based on backend-supplied [status] strings only.
/// Flutter never assigns, computes, or infers status values.
class ContentStatusGuard {
  const ContentStatusGuard._();

  /// The only status value that is safe to render in the student app.
  static const String _published = 'published';

  /// Returns true if [status] is exactly 'published'.
  ///
  /// [status] is always a backend-supplied string; never generated by Flutter.
  static bool isPublished(String status) => status == _published;

  /// Filters a list of [CourseModel] to include only published items.
  static List<CourseModel> filterCourses(List<CourseModel> courses) =>
      courses.where((c) => isPublished(c.status)).toList();

  /// Filters a list of [LevelModel] to include only published items.
  static List<LevelModel> filterLevels(List<LevelModel> levels) =>
      levels.where((l) => isPublished(l.status)).toList();

  /// Filters a list of [ChapterModel] to include only published items.
  static List<ChapterModel> filterChapters(List<ChapterModel> chapters) =>
      chapters.where((c) => isPublished(c.status)).toList();

  /// Filters a list of [LessonModel] to include only published items.
  static List<LessonModel> filterLessons(List<LessonModel> lessons) =>
      lessons.where((l) => isPublished(l.status)).toList();

  /// Filters a list of [LessonAsset] to include only published items.
  ///
  /// Note: the datasource (P6-077) already requests status=published; this
  /// guard is a second defensive layer.
  static List<LessonAsset> filterAssets(List<LessonAsset> assets) =>
      assets.where((a) => isPublished(a.status)).toList();
}
