// Phase 3 — P3-047
// Curriculum error codes for request/payload validation.
//
// Source of truth: packages/shared-contracts/api/errors.md
// (Phase 3 — Curriculum Error Codes, defined under P3-016).
//
// This enum mirrors the documented codes so backend validators can return
// stable, client-safe error codes. Only codes relevant to request payload
// validation (this task, P3-047) are required here; the full set is kept so
// downstream tasks (publish validation, status workflow, etc.) can reuse the
// same enum without redefining codes.

export enum CurriculumErrorCode {
  // Course
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  COURSE_TITLE_REQUIRED = 'COURSE_TITLE_REQUIRED',
  COURSE_DESCRIPTION_REQUIRED = 'COURSE_DESCRIPTION_REQUIRED',
  COURSE_SLUG_CONFLICT = 'COURSE_SLUG_CONFLICT',
  COURSE_PUBLISH_REQUIREMENTS_NOT_MET = 'COURSE_PUBLISH_REQUIREMENTS_NOT_MET',
  COURSE_HAS_NO_PUBLISHED_LEVEL = 'COURSE_HAS_NO_PUBLISHED_LEVEL',
  COURSE_ARCHIVED_NOT_EDITABLE = 'COURSE_ARCHIVED_NOT_EDITABLE',
  COURSE_INVALID_STATUS_TRANSITION = 'COURSE_INVALID_STATUS_TRANSITION',

  // Level
  LEVEL_NOT_FOUND = 'LEVEL_NOT_FOUND',
  LEVEL_TITLE_REQUIRED = 'LEVEL_TITLE_REQUIRED',
  LEVEL_COURSE_NOT_FOUND = 'LEVEL_COURSE_NOT_FOUND',
  LEVEL_COURSE_ARCHIVED = 'LEVEL_COURSE_ARCHIVED',
  LEVEL_PUBLISH_REQUIREMENTS_NOT_MET = 'LEVEL_PUBLISH_REQUIREMENTS_NOT_MET',
  LEVEL_HAS_NO_PUBLISHED_CHAPTER = 'LEVEL_HAS_NO_PUBLISHED_CHAPTER',
  LEVEL_COURSE_NOT_PUBLISHED = 'LEVEL_COURSE_NOT_PUBLISHED',
  LEVEL_ARCHIVED_NOT_EDITABLE = 'LEVEL_ARCHIVED_NOT_EDITABLE',
  LEVEL_ORDER_CONFLICT = 'LEVEL_ORDER_CONFLICT',
  LEVEL_INVALID_STATUS_TRANSITION = 'LEVEL_INVALID_STATUS_TRANSITION',

  // Chapter
  CHAPTER_NOT_FOUND = 'CHAPTER_NOT_FOUND',
  CHAPTER_TITLE_REQUIRED = 'CHAPTER_TITLE_REQUIRED',
  CHAPTER_LEVEL_NOT_FOUND = 'CHAPTER_LEVEL_NOT_FOUND',
  CHAPTER_LEVEL_ARCHIVED = 'CHAPTER_LEVEL_ARCHIVED',
  CHAPTER_PUBLISH_REQUIREMENTS_NOT_MET = 'CHAPTER_PUBLISH_REQUIREMENTS_NOT_MET',
  CHAPTER_HAS_NO_PUBLISHED_LESSON = 'CHAPTER_HAS_NO_PUBLISHED_LESSON',
  CHAPTER_LEVEL_NOT_PUBLISHED = 'CHAPTER_LEVEL_NOT_PUBLISHED',
  CHAPTER_ARCHIVED_NOT_EDITABLE = 'CHAPTER_ARCHIVED_NOT_EDITABLE',
  CHAPTER_ORDER_CONFLICT = 'CHAPTER_ORDER_CONFLICT',
  CHAPTER_INVALID_STATUS_TRANSITION = 'CHAPTER_INVALID_STATUS_TRANSITION',

  // Lesson
  LESSON_NOT_FOUND = 'LESSON_NOT_FOUND',
  LESSON_TITLE_REQUIRED = 'LESSON_TITLE_REQUIRED',
  LESSON_DESCRIPTION_REQUIRED = 'LESSON_DESCRIPTION_REQUIRED',
  LESSON_CHAPTER_NOT_FOUND = 'LESSON_CHAPTER_NOT_FOUND',
  LESSON_CHAPTER_ARCHIVED = 'LESSON_CHAPTER_ARCHIVED',
  LESSON_PUBLISH_REQUIREMENTS_NOT_MET = 'LESSON_PUBLISH_REQUIREMENTS_NOT_MET',
  LESSON_MISSING_SKILL = 'LESSON_MISSING_SKILL',
  LESSON_MISSING_ASSET = 'LESSON_MISSING_ASSET',
  LESSON_SKILL_NOT_PUBLISHED = 'LESSON_SKILL_NOT_PUBLISHED',
  LESSON_ARCHIVED_NOT_EDITABLE = 'LESSON_ARCHIVED_NOT_EDITABLE',
  LESSON_ORDER_CONFLICT = 'LESSON_ORDER_CONFLICT',
  LESSON_INVALID_STATUS_TRANSITION = 'LESSON_INVALID_STATUS_TRANSITION',
  LESSON_CHAPTER_ID_IMMUTABLE = 'LESSON_CHAPTER_ID_IMMUTABLE',

  // Skill
  SKILL_NOT_FOUND = 'SKILL_NOT_FOUND',
  SKILL_KEY_REQUIRED = 'SKILL_KEY_REQUIRED',
  SKILL_KEY_INVALID = 'SKILL_KEY_INVALID',
  SKILL_KEY_CONFLICT = 'SKILL_KEY_CONFLICT',
  SKILL_TITLE_REQUIRED = 'SKILL_TITLE_REQUIRED',
  SKILL_PUBLISH_REQUIREMENTS_NOT_MET = 'SKILL_PUBLISH_REQUIREMENTS_NOT_MET',
  SKILL_HAS_NO_OBJECTIVE = 'SKILL_HAS_NO_OBJECTIVE',
  SKILL_ARCHIVED_NOT_EDITABLE = 'SKILL_ARCHIVED_NOT_EDITABLE',
  SKILL_INVALID_STATUS_TRANSITION = 'SKILL_INVALID_STATUS_TRANSITION',
  SKILL_DOMAIN_INVALID = 'SKILL_DOMAIN_INVALID',

  // Objective
  OBJECTIVE_NOT_FOUND = 'OBJECTIVE_NOT_FOUND',
  OBJECTIVE_TEXT_REQUIRED = 'OBJECTIVE_TEXT_REQUIRED',
  OBJECTIVE_SKILL_NOT_FOUND = 'OBJECTIVE_SKILL_NOT_FOUND',
  OBJECTIVE_SKILL_ARCHIVED = 'OBJECTIVE_SKILL_ARCHIVED',
  OBJECTIVE_SKILL_NOT_PUBLISHED = 'OBJECTIVE_SKILL_NOT_PUBLISHED',
  OBJECTIVE_ARCHIVED_NOT_EDITABLE = 'OBJECTIVE_ARCHIVED_NOT_EDITABLE',
  OBJECTIVE_INVALID_STATUS_TRANSITION = 'OBJECTIVE_INVALID_STATUS_TRANSITION',

  // Lesson Asset
  ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',
  ASSET_LESSON_NOT_FOUND = 'ASSET_LESSON_NOT_FOUND',
  ASSET_INVALID_TYPE = 'ASSET_INVALID_TYPE',
  ASSET_MISSING_URL = 'ASSET_MISSING_URL',
  ASSET_TITLE_REQUIRED = 'ASSET_TITLE_REQUIRED',
  ASSET_MISSING_ALT_TEXT = 'ASSET_MISSING_ALT_TEXT',
  ASSET_ORDER_CONFLICT = 'ASSET_ORDER_CONFLICT',
  ASSET_LESSON_ARCHIVED = 'ASSET_LESSON_ARCHIVED',
  ASSET_ARCHIVED_NOT_EDITABLE = 'ASSET_ARCHIVED_NOT_EDITABLE',
  ASSET_LESSON_ID_IMMUTABLE = 'ASSET_LESSON_ID_IMMUTABLE',
  ASSET_TYPE_IMMUTABLE = 'ASSET_TYPE_IMMUTABLE',
  ASSET_INVALID_STATUS_TRANSITION = 'ASSET_INVALID_STATUS_TRANSITION',

  // Question Bank
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  QUESTION_MISSING_STEM = 'QUESTION_MISSING_STEM',
  QUESTION_INVALID_TYPE = 'QUESTION_INVALID_TYPE',
  QUESTION_INVALID_DIFFICULTY = 'QUESTION_INVALID_DIFFICULTY',
  QUESTION_NO_PRIMARY_SKILL = 'QUESTION_NO_PRIMARY_SKILL',
  QUESTION_SKILL_NOT_PUBLISHED = 'QUESTION_SKILL_NOT_PUBLISHED',
  QUESTION_NO_CORRECT_ANSWER = 'QUESTION_NO_CORRECT_ANSWER',
  QUESTION_CHOICE_CONFLICT = 'QUESTION_CHOICE_CONFLICT',
  QUESTION_TRUE_FALSE_INVALID = 'QUESTION_TRUE_FALSE_INVALID',
  QUESTION_CHOICE_ORDER_CONFLICT = 'QUESTION_CHOICE_ORDER_CONFLICT',
  QUESTION_ANSWER_TYPE_MISMATCH = 'QUESTION_ANSWER_TYPE_MISMATCH',
  QUESTION_ARCHIVED_NOT_EDITABLE = 'QUESTION_ARCHIVED_NOT_EDITABLE',
  QUESTION_TYPE_IMMUTABLE = 'QUESTION_TYPE_IMMUTABLE',
  QUESTION_INVALID_STATUS_TRANSITION = 'QUESTION_INVALID_STATUS_TRANSITION',

  // Content Status Lifecycle (shared across all entities)
  CONTENT_ALREADY_PUBLISHED = 'CONTENT_ALREADY_PUBLISHED',
  CONTENT_ALREADY_ARCHIVED = 'CONTENT_ALREADY_ARCHIVED',
  CONTENT_PUBLISH_REQUIREMENTS_NOT_MET = 'CONTENT_PUBLISH_REQUIREMENTS_NOT_MET',
  CONTENT_ARCHIVED_NOT_EDITABLE = 'CONTENT_ARCHIVED_NOT_EDITABLE',
  CONTENT_RESTORE_FORBIDDEN = 'CONTENT_RESTORE_FORBIDDEN',
  CONTENT_INVALID_TRANSITION = 'CONTENT_INVALID_TRANSITION',

  // Curriculum Hierarchy
  CURRICULUM_PARENT_NOT_FOUND = 'CURRICULUM_PARENT_NOT_FOUND',
  CURRICULUM_PARENT_NOT_PUBLISHED = 'CURRICULUM_PARENT_NOT_PUBLISHED',
  CURRICULUM_PARENT_ARCHIVED = 'CURRICULUM_PARENT_ARCHIVED',
  CURRICULUM_SLUG_CONFLICT = 'CURRICULUM_SLUG_CONFLICT',
  CURRICULUM_ORDER_CONFLICT = 'CURRICULUM_ORDER_CONFLICT',
  CURRICULUM_STATUS_TRANSITION_INVALID = 'CURRICULUM_STATUS_TRANSITION_INVALID',
  CURRICULUM_PERMISSION_DENIED = 'CURRICULUM_PERMISSION_DENIED',
  CURRICULUM_CASCADE_BLOCKED = 'CURRICULUM_CASCADE_BLOCKED',
  CURRICULUM_HIERARCHY_INVALID = 'CURRICULUM_HIERARCHY_INVALID',

  // Lesson-Skill Linking
  LESSON_SKILL_LINK_NOT_FOUND = 'LESSON_SKILL_LINK_NOT_FOUND',
  LESSON_SKILL_LINK_ALREADY_EXISTS = 'LESSON_SKILL_LINK_ALREADY_EXISTS',
  LESSON_SKILL_LINK_SKILL_ARCHIVED = 'LESSON_SKILL_LINK_SKILL_ARCHIVED',
  LESSON_SKILL_LAST_LINK_PROTECTED = 'LESSON_SKILL_LAST_LINK_PROTECTED',
}
