export enum AiTeacherMode {
  EXPLAIN_MORE = 'EXPLAIN_MORE',
  GIVE_EXAMPLE = 'GIVE_EXAMPLE',
  EXPLAIN_WHY = 'EXPLAIN_WHY',
  REMEDIATION = 'REMEDIATION',
}

export enum AiTeacherValidationStatus {
  PASSED = 'PASSED',
  FAILED_PROHIBITED_LANGUAGE = 'FAILED_PROHIBITED_LANGUAGE',
  FAILED_OFF_TOPIC = 'FAILED_OFF_TOPIC',
  FAILED_ANSWER_LEAKAGE = 'FAILED_ANSWER_LEAKAGE',
  FAILED_EXCESSIVE_LENGTH = 'FAILED_EXCESSIVE_LENGTH',
  FALLBACK_USED = 'FALLBACK_USED',
}
