// Phase 6 — P6-080
// lesson_content_renderer_test.dart — widget tests for LessonContentRenderer.
//
// Covers:
//   1. image type renders Image.network (or error fallback — no network in test).
//   2. audio type renders title without crash.
//   3. video type renders title without crash.
//   4. document type renders title without crash.
//   5. external_reference type renders title without crash.
//   6. Unknown type renders without crash (fallback card).
//   7. durationSeconds formatted as mm:ss in audio card.
//   8. altText is not generated by Flutter (assert backend value used).
//   9. RTL layout renders without error.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:aim_mobile/core/localization/localization.dart';
import 'package:aim_mobile/core/theme/app_theme.dart';
import 'package:aim_mobile/features/lessons/data/models/lessons_models.dart';
import 'package:aim_mobile/features/lessons/ui/widgets/lesson_content_renderer.dart';

// ── Helpers ───────────────────────────────────────────────────────────────────

Widget _wrap(Widget child, {TextDirection dir = TextDirection.ltr}) =>
    MaterialApp(
      theme: AppTheme.light,
      localizationsDelegates: AppLocale.delegates,
      supportedLocales: AppLocale.supportedLocales,
      home: Scaffold(
        body: Directionality(
          textDirection: dir,
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: child,
          ),
        ),
      ),
    );

LessonAssetModel _asset({
  required String type,
  String? url,
  String? altText,
  int? durationSeconds,
  String? description,
}) =>
    LessonAssetModel.fromJson({
      'id': 'asset-1',
      'lessonId': 'lesson-1',
      'type': type,
      'title': '$type asset title',
      'description': description,
      'url': url,
      'mimeType': null,
      'sizeBytes': null,
      'durationSeconds': durationSeconds,
      'altText': altText,
      'thumbnailUrl': null,
      'order': 1,
      'status': 'published',
      'metadata': null,
      'createdAt': '2025-01-01T00:00:00Z',
      'updatedAt': '2025-06-01T00:00:00Z',
    });

// ── Tests ─────────────────────────────────────────────────────────────────────

void main() {
  group('LessonContentRenderer', () {
    testWidgets('image type renders without crash', (tester) async {
      await tester.pumpWidget(_wrap(
        LessonContentRenderer(
          asset: _asset(
            type: 'image',
            url: 'https://cdn.example.com/img.png',
            altText: 'Backend-supplied alt text.',
          ),
        ),
      ));
      await tester.pump();
      expect(find.byType(LessonContentRenderer), findsOneWidget);
    });

    testWidgets('image with missing url renders error card', (tester) async {
      await tester.pumpWidget(_wrap(
        LessonContentRenderer(asset: _asset(type: 'image', url: null)),
      ));
      await tester.pump();
      expect(find.textContaining('Image URL is missing'), findsOneWidget);
    });

    testWidgets('audio type renders title without crash', (tester) async {
      await tester.pumpWidget(_wrap(
        LessonContentRenderer(
          asset: _asset(type: 'audio', url: 'https://cdn.example.com/audio.mp3'),
        ),
      ));
      await tester.pump();
      expect(find.text('audio asset title'), findsOneWidget);
    });

    testWidgets('video type renders title without crash', (tester) async {
      await tester.pumpWidget(_wrap(
        LessonContentRenderer(
          asset: _asset(type: 'video', url: 'https://cdn.example.com/video.mp4'),
        ),
      ));
      await tester.pump();
      expect(find.text('video asset title'), findsOneWidget);
    });

    testWidgets('document type renders title without crash', (tester) async {
      await tester.pumpWidget(_wrap(
        LessonContentRenderer(asset: _asset(type: 'document')),
      ));
      await tester.pump();
      expect(find.text('document asset title'), findsOneWidget);
    });

    testWidgets('external_reference type renders title without crash',
        (tester) async {
      await tester.pumpWidget(_wrap(
        LessonContentRenderer(
          asset: _asset(type: 'external_reference',
              url: 'https://example.com/resource'),
        ),
      ));
      await tester.pump();
      expect(find.text('external_reference asset title'), findsOneWidget);
    });

    testWidgets('unknown type renders fallback without crash', (tester) async {
      await tester.pumpWidget(_wrap(
        LessonContentRenderer(asset: _asset(type: 'unknown_future_type')),
      ));
      await tester.pump();
      expect(find.byType(LessonContentRenderer), findsOneWidget);
    });

    testWidgets('audio durationSeconds displayed as mm:ss', (tester) async {
      await tester.pumpWidget(_wrap(
        LessonContentRenderer(
          asset: _asset(
            type: 'audio',
            url: 'https://cdn.example.com/audio.mp3',
            durationSeconds: 125, // 2m 05s
          ),
        ),
      ));
      await tester.pump();
      expect(find.text('02:05'), findsOneWidget);
    });

    testWidgets('renders without error under RTL directionality', (tester) async {
      await tester.pumpWidget(_wrap(
        LessonContentRenderer(
          asset: _asset(type: 'document', description: 'Reading material.'),
        ),
        dir: TextDirection.rtl,
      ));
      await tester.pump();
      expect(find.byType(LessonContentRenderer), findsOneWidget);
      expect(find.text('document asset title'), findsOneWidget);
    });
  });
}
