-- P4-024: Create Initial Learning Path Migration
-- Branch: phase4/P4-024-initial-learning-path-migration
-- Dependency: P4-015 (Initial Learning Path Contract), P4-023 (placement_results table)
-- Scope: initial_learning_path table only. No AIM Engine runtime. No lesson delivery.

-- ============================================================
-- Table: initial_learning_path
-- ============================================================
-- Stores one ordered entry per curriculum entry point derived
-- from a completed placement result. Written once by the backend
-- immediately after the placement result is finalised.
-- Never modified after creation. Retakes produce a new result
-- and a new set of path entries.

CREATE TABLE initial_learning_path (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    placement_result_id     UUID            NOT NULL REFERENCES placement_results (id) ON DELETE CASCADE,
    priority                INTEGER         NOT NULL CHECK (priority > 0),
    entry_type              TEXT            NOT NULL
                                            CHECK (entry_type IN ('section', 'skill')),
    skill_code              TEXT            NULL,
    skill_id                UUID            NULL REFERENCES skills (id) ON DELETE SET NULL,
    skill_key               TEXT            NULL,
    skill_name              TEXT            NOT NULL,
    estimated_level         TEXT            NOT NULL
                                            CHECK (estimated_level IN ('A1', 'A2', 'B1')),
    source                  TEXT            NOT NULL
                                            CHECK (source IN ('weakness_map', 'fallback')),
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE initial_learning_path IS
    'Ordered list of curriculum entry points derived from a completed placement result. '
    'Written once by the backend after result finalisation. Immutable after creation. '
    'Scope: Phase 4 Placement Test only. Not lesson delivery or progress dashboard.';

COMMENT ON COLUMN initial_learning_path.id IS
    'Primary key — UUID generated by backend.';

COMMENT ON COLUMN initial_learning_path.placement_result_id IS
    'Foreign key to placement_results — the result this path belongs to.';

COMMENT ON COLUMN initial_learning_path.priority IS
    'Rank order within the path. 1 = highest priority. Must be positive and unique per placement_result_id.';

COMMENT ON COLUMN initial_learning_path.entry_type IS
    'Type of curriculum entry point: section (skill code area) or skill (specific skill record).';

COMMENT ON COLUMN initial_learning_path.skill_code IS
    'Section skill code for section-type entries (e.g. grammar, vocabulary). Null for skill-type entries.';

COMMENT ON COLUMN initial_learning_path.skill_id IS
    'FK to skills table for skill-type entries. Null for section-type entries. '
    'Never exposed to Flutter — internal identifier only.';

COMMENT ON COLUMN initial_learning_path.skill_key IS
    'Dot-delimited stable skill key from P3-006 (e.g. grammar.past_simple.forms). '
    'Null for section-type entries. Never exposed to Flutter — internal identifier only.';

COMMENT ON COLUMN initial_learning_path.skill_name IS
    'Human-readable display name. The only name field returned to Flutter.';

COMMENT ON COLUMN initial_learning_path.estimated_level IS
    'CEFR level annotation from placement_results: A1, A2, or B1. '
    'Informational only — does not alter priority order.';

COMMENT ON COLUMN initial_learning_path.source IS
    'Derivation source: weakness_map (from ranked weakness entries) or fallback '
    '(applied when weakness map is empty). Internal metadata — never exposed to Flutter.';

COMMENT ON COLUMN initial_learning_path.created_at IS
    'Timestamp when the path entry was written by the backend — never modified.';

-- ============================================================
-- Constraint: priority unique per placement result
-- ============================================================

CREATE UNIQUE INDEX initial_learning_path_result_priority_idx
    ON initial_learning_path (placement_result_id, priority);

-- ============================================================
-- Constraint: section-type entries must have skill_code
-- ============================================================

ALTER TABLE initial_learning_path
    ADD CONSTRAINT initial_learning_path_section_requires_skill_code
    CHECK (
        entry_type <> 'section' OR skill_code IS NOT NULL
    );

-- ============================================================
-- Constraint: skill-type entries must have skill_id and skill_key
-- ============================================================

ALTER TABLE initial_learning_path
    ADD CONSTRAINT initial_learning_path_skill_requires_skill_id
    CHECK (
        entry_type <> 'skill' OR (skill_id IS NOT NULL AND skill_key IS NOT NULL)
    );

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX initial_learning_path_result_id_idx
    ON initial_learning_path (placement_result_id);

CREATE INDEX initial_learning_path_result_priority_ordered_idx
    ON initial_learning_path (placement_result_id, priority ASC);

CREATE INDEX initial_learning_path_entry_type_idx
    ON initial_learning_path (entry_type);

CREATE INDEX initial_learning_path_skill_id_idx
    ON initial_learning_path (skill_id)
    WHERE skill_id IS NOT NULL;
