// Design ref: docs/design/ui-for-all-system-mobile/SCREENS.md → "Splash"
//   docs/design/ui-for-all-system-mobile/screenshots/light/01-screen.png
//   docs/design/ui-for-all-system-mobile/screenshots/dark/01-screen.png
// Endpoint: none (static loading/branding screen, real auth-check state
//   from authFlowProvider)
// Widgets: AuthGate, LinearProgressIndicator (custom-styled), Stack/Positioned
//   decorative circles
//
// Two-stage splash strategy:
//   Stage 1 (native): Android launch_background.xml / iOS
//   LaunchScreen.storyboard show a static gradient + centered icon badge,
//   generated by `dart run flutter_native_splash:create` from
//   assets/splash/splash_background.png and assets/splash/splash_logo.png —
//   both are direct renders of AimGradients.gzHero and the exact badge below,
//   so the native frame and this page's first frame are pixel-identical.
//   main.dart calls FlutterNativeSplash.preserve() before runApp(), so the
//   native splash stays on screen (no white flash) until this page removes
//   it explicitly.
//   Stage 2 (this widget): the badge is pinned at Alignment.center for its
//   entire lifetime — on both platforms it never moves, so nothing here can
//   ever visibly jump relative to the native frame it replaces. Everything
//   else (title, subtitle, decorative circles, progress bar) starts
//   invisible — matching native exactly, which shows none of it — and only
//   fades/slides in on the frame *after* FlutterNativeSplash.remove() is
//   called, so frame 0 is a true match and the animation is what visibly
//   starts the "Flutter stage".
import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/theme/theme.dart';
import '../../../../core/widgets/widgets.dart';
import '../../../auth/logic/provider/auth_flow_provider.dart';
import '../../../auth/ui/widgets/auth_gate.dart';

/// Splash / bootstrap screen — Student Mobile App MVP.
///
/// Purely a branding + loading surface: the real auth-check work and the
/// resulting navigation are entirely owned by [AuthGate], which is mounted
/// unchanged in the [Stack] below. This widget only renders the gradient
/// hero, brand mark, and a progress affordance driven by
/// [authFlowProvider]'s `isChecking` flag — it never makes navigation
/// decisions itself.
///
/// Design system: all colours, typography, spacing use AIM Mobile Design
/// System tokens. No hard-coded values except the documented translucent
/// white overlays used for the decorative circles / icon badge, matching
/// the pattern already established in `register_page.dart` / `login_page.dart`
/// for gradient-hero back buttons.
class SplashPage extends ConsumerStatefulWidget {
  const SplashPage({super.key});

  @override
  ConsumerState<SplashPage> createState() => _SplashPageState();
}

class _SplashPageState extends ConsumerState<SplashPage>
    with SingleTickerProviderStateMixin {
  late final AnimationController _controller;
  late final Animation<double> _titleOpacity;
  late final Animation<Offset> _titleSlide;
  late final Animation<double> _progressOpacity;
  late final Animation<Offset> _progressSlide;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 900),
    );
    _titleOpacity = CurvedAnimation(
      parent: _controller,
      curve: const Interval(0.0, 0.65, curve: Curves.easeOut),
    );
    _titleSlide = Tween<Offset>(
      begin: const Offset(0, 0.12),
      end: Offset.zero,
    ).animate(CurvedAnimation(
      parent: _controller,
      curve: const Interval(0.0, 0.65, curve: Curves.easeOutCubic),
    ));
    _progressOpacity = CurvedAnimation(
      parent: _controller,
      curve: const Interval(0.35, 1.0, curve: Curves.easeOut),
    );
    _progressSlide = Tween<Offset>(
      begin: const Offset(0, 0.12),
      end: Offset.zero,
    ).animate(CurvedAnimation(
      parent: _controller,
      curve: const Interval(0.35, 1.0, curve: Curves.easeOutCubic),
    ));

    // At this point the first frame — gradient + centered badge, with
    // everything below still at its t=0 (invisible) animation value — has
    // already painted and is pixel-identical to the native splash. Only now
    // is it safe to remove the native splash and begin animating.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      FlutterNativeSplash.remove();
      _controller.forward();
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final authState = ref.watch(authFlowProvider);

    return Scaffold(
      body: Stack(
        children: [
          // ── Gradient hero background ─────────────────────────────────
          const DecoratedBox(
            decoration: BoxDecoration(gradient: AimGradients.gzHero),
            child: SizedBox.expand(),
          ),

          // ── Decorative blurred circles — Flutter-only, fades in ──────
          FadeTransition(
            opacity: _titleOpacity,
            child: const Stack(
              children: [
                Positioned(
                  top: -60,
                  right: -40,
                  child: _DecorativeCircle(size: 220, opacity: 0.15),
                ),
                Positioned(
                  left: -70,
                  top: 220,
                  child: _DecorativeCircle(size: 150, opacity: 0.12),
                ),
                Positioned(
                  bottom: -50,
                  left: -30,
                  child: _DecorativeCircle(size: 200, opacity: 0.12),
                ),
              ],
            ),
          ),

          // ── Real auth-check + navigation (unchanged, untouched) ──────
          const AuthGate(),

          // ── Icon badge — fixed at dead-center for its entire lifetime.
          // This is the one element the native splash also draws (via
          // assets/splash/splash_logo.png), so it must never move or
          // animate; that's what keeps the native → Flutter handoff from
          // ever visibly jumping.
          const Center(child: _SplashBadge()),

          // ── "AIM" title + subtitle — Flutter-only, revealed just below
          // the fixed badge once the native splash has been removed.
          Align(
            alignment: const Alignment(0, 0.32),
            child: FadeTransition(
              opacity: _titleOpacity,
              child: SlideTransition(
                position: _titleSlide,
                child: Padding(
                  padding: const EdgeInsets.symmetric(
                    horizontal: AimSpacing.screenPaddingMobile,
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        'AIM',
                        style: AimTextStyles.display.copyWith(
                          color: AimColors.neutral0,
                          letterSpacing: 2,
                        ),
                      ),
                      const SizedBox(height: AimSpacing.innerGap),
                      Text(
                        'Adaptive Intelligence for Mastery',
                        style: AimTextStyles.bodySm.copyWith(
                          color: AimColors.neutral0.withValues(alpha: 0.85),
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),

          // ── Progress + hint — Flutter-only, pinned near the bottom ───
          // The real auth-check flow is fully automatic: AuthGate
          // reactively navigates away as soon as authFlowProvider
          // resolves, and there is no working "tap to skip" mechanism
          // anywhere in this codebase. Rather than invent one (out of
          // scope for a visual fix) or wire a fake onTap that does
          // nothing, "Tap to continue" is rendered as static,
          // non-interactive copy shown alongside the progress bar for
          // the whole duration of the check — matching the mockup's
          // simultaneous appearance of both elements — and it never
          // receives a tap handler.
          if (authState.isChecking)
            Positioned(
              left: 0,
              right: 0,
              bottom: 0,
              child: SafeArea(
                child: Padding(
                  padding: const EdgeInsets.all(
                    AimSpacing.screenPaddingMobile,
                  ),
                  child: FadeTransition(
                    opacity: _progressOpacity,
                    child: SlideTransition(
                      position: _progressSlide,
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          ClipRRect(
                            borderRadius: AimRadius.borderPill,
                            child: SizedBox(
                              height: AimSpacing.space4,
                              width: double.infinity,
                              child: LinearProgressIndicator(
                                backgroundColor: AimColors.neutral0
                                    .withValues(alpha: 0.25),
                                valueColor:
                                    const AlwaysStoppedAnimation<Color>(
                                  AimColors.neutral0,
                                ),
                              ),
                            ),
                          ),
                          const SizedBox(height: AimSpacing.componentGap),
                          Text(
                            'Tap to continue',
                            style: AimTextStyles.caption.copyWith(
                              color: AimColors.neutral0.withValues(
                                alpha: 0.75,
                              ),
                            ),
                            textAlign: TextAlign.center,
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}

/// The icon badge with sparkle accent — identical to
/// assets/splash/splash_logo.png (the native splash's logo image). Kept as
/// its own widget so both are visibly generated from the same design, even
/// though the native asset is a separate pre-rendered PNG (native launch
/// screens can't render live Flutter widgets).
class _SplashBadge extends StatelessWidget {
  const _SplashBadge();

  @override
  Widget build(BuildContext context) {
    return Stack(
      clipBehavior: Clip.none,
      children: [
        DecoratedBox(
          decoration: BoxDecoration(
            color: AimColors.neutral0.withValues(alpha: 0.18),
            borderRadius: AimRadius.borderXl,
          ),
          child: const Padding(
            padding: EdgeInsets.all(AimSpacing.space24),
            child: Icon(
              Icons.school_outlined,
              size: AimSizes.iconLg * 1.5,
              color: AimColors.neutral0,
            ),
          ),
        ),
        const PositionedDirectional(
          top: -6,
          end: -6,
          child: Icon(
            Icons.auto_awesome,
            size: AimSizes.iconSm,
            color: AimColors.warning500,
          ),
        ),
      ],
    );
  }
}

/// A soft, translucent decorative circle used to echo the mockup's blurred
/// background blobs. Purely visual — no data, no interaction.
class _DecorativeCircle extends StatelessWidget {
  const _DecorativeCircle({required this.size, required this.opacity});

  final double size;
  final double opacity;

  @override
  Widget build(BuildContext context) {
    return DecoratedBox(
      decoration: BoxDecoration(
        color: AimColors.neutral0.withValues(alpha: opacity),
        shape: BoxShape.circle,
      ),
      child: SizedBox(width: size, height: size),
    );
  }
}
