-- P4-025: Create Placement Audit Log Migration
-- Branch: phase4/P4-025-placement-audit-log-migration
-- Dependency: P4-021 (Placement Attempts Migration)
-- Scope: Placement audit log table only. No AIM Engine runtime.

-- ============================================================
-- Table: placement_audit_log
-- ============================================================

CREATE TABLE placement_audit_log (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    placement_attempt_id    UUID            NULL REFERENCES placement_attempts (id) ON DELETE SET NULL,
    student_id              UUID            NOT NULL,
    event_type              TEXT            NOT NULL
                                            CHECK (event_type IN (
                                                'attempt_started',
                                                'answer_submitted',
                                                'attempt_submitted',
                                                'attempt_completed',
                                                'attempt_abandoned',
                                                'result_generated',
                                                'path_assigned'
                                            )),
    event_data              JSONB           NOT NULL DEFAULT '{}',
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE placement_audit_log IS
    'Audit trail for placement lifecycle events. Supports debugging and accountability.';

COMMENT ON COLUMN placement_audit_log.id IS
    'Primary key — UUID generated by backend.';

COMMENT ON COLUMN placement_audit_log.placement_attempt_id IS
    'Foreign key to placement_attempts — nullable in case attempt is deleted.';

COMMENT ON COLUMN placement_audit_log.student_id IS
    'Student who triggered the event — denormalized for fast lookup.';

COMMENT ON COLUMN placement_audit_log.event_type IS
    'Type of placement lifecycle event. One of the allowed values.';

COMMENT ON COLUMN placement_audit_log.event_data IS
    'JSONB payload with event-specific details for debugging.';

COMMENT ON COLUMN placement_audit_log.created_at IS
    'Timestamp when the event was recorded — set by backend.';

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX placement_audit_log_attempt_id_idx
    ON placement_audit_log (placement_attempt_id);

CREATE INDEX placement_audit_log_student_id_idx
    ON placement_audit_log (student_id);

CREATE INDEX placement_audit_log_event_type_idx
    ON placement_audit_log (event_type);

CREATE INDEX placement_audit_log_created_at_idx
    ON placement_audit_log (created_at);