-- P4-021: Create Placement Attempts Migration
-- Branch: phase4/P4-021-placement-attempts-migration
-- Dependency: P4-013 (Placement Attempt Contract)
-- Scope: Placement attempts table only. No AIM Engine runtime.

-- ============================================================
-- Table: placement_attempts
-- ============================================================

CREATE TABLE placement_attempts (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id          UUID            NOT NULL,
    placement_test_id   UUID            NOT NULL REFERENCES placement_tests (id) ON DELETE CASCADE,
    status              TEXT            NOT NULL DEFAULT 'active'
                                        CHECK (status IN ('active', 'submitted', 'completed', 'abandoned')),
    started_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    submitted_at        TIMESTAMPTZ     NULL,
    completed_at        TIMESTAMPTZ     NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE placement_attempts IS
    'Tracks each student placement test attempt. One active attempt per student per test allowed at a time.';

COMMENT ON COLUMN placement_attempts.id IS
    'Primary key — UUID generated by backend.';

COMMENT ON COLUMN placement_attempts.student_id IS
    'Foreign key to students table — set by backend on attempt start.';

COMMENT ON COLUMN placement_attempts.placement_test_id IS
    'Foreign key to placement_tests — the test this attempt belongs to.';

COMMENT ON COLUMN placement_attempts.status IS
    'Attempt lifecycle status. Transitions: active -> submitted -> completed. active -> abandoned on timeout.';

COMMENT ON COLUMN placement_attempts.started_at IS
    'Timestamp when the attempt was started — set by backend.';

COMMENT ON COLUMN placement_attempts.submitted_at IS
    'Timestamp when the student submitted the attempt — null until submitted.';

COMMENT ON COLUMN placement_attempts.completed_at IS
    'Timestamp when backend completed evaluation — null until completed.';

-- ============================================================
-- Constraint: one active attempt per student per test
-- ============================================================

CREATE UNIQUE INDEX placement_attempts_active_unique_idx
    ON placement_attempts (student_id, placement_test_id)
    WHERE status = 'active';

-- ============================================================
-- Trigger: auto-update updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION update_placement_attempts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER placement_attempts_updated_at_trigger
    BEFORE UPDATE ON placement_attempts
    FOR EACH ROW
    EXECUTE FUNCTION update_placement_attempts_updated_at();

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX placement_attempts_student_id_idx
    ON placement_attempts (student_id);

CREATE INDEX placement_attempts_test_id_idx
    ON placement_attempts (placement_test_id);

CREATE INDEX placement_attempts_status_idx
    ON placement_attempts (status);

CREATE INDEX placement_attempts_student_test_idx
    ON placement_attempts (student_id, placement_test_id);