/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects.
// It is committed here to keep the Phase 1 shell typecheckable before first local run.
