-- P4-022: Create Placement Answers Migration
-- Branch: phase4/P4-022-placement-answers-migration
-- Dependency: P4-012 (Placement Answer Contract), P4-021 (Placement Attempts Migration)
-- Scope: Placement answers table only. No AIM Engine runtime.

-- ============================================================
-- Table: placement_answers
-- ============================================================

CREATE TABLE placement_answers (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    placement_attempt_id    UUID            NOT NULL REFERENCES placement_attempts (id) ON DELETE CASCADE,
    placement_question_id   UUID            NOT NULL REFERENCES placement_questions (id) ON DELETE CASCADE,
    answer_value            TEXT            NOT NULL CHECK (LENGTH(TRIM(answer_value)) > 0),
    is_correct              BOOLEAN         NULL,
    skill_code              TEXT            NOT NULL
                                            CHECK (skill_code IN ('grammar', 'vocabulary', 'reading', 'listening')),
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE placement_answers IS
    'Stores answers submitted by students during a placement attempt. One answer per question per attempt.';

COMMENT ON COLUMN placement_answers.id IS
    'Primary key — UUID generated by backend.';

COMMENT ON COLUMN placement_answers.placement_attempt_id IS
    'Foreign key to placement_attempts — the attempt this answer belongs to.';

COMMENT ON COLUMN placement_answers.placement_question_id IS
    'Foreign key to placement_questions — the question being answered.';

COMMENT ON COLUMN placement_answers.answer_value IS
    'The student submitted answer. Format depends on question type per P4-012 contract.';

COMMENT ON COLUMN placement_answers.is_correct IS
    'Evaluated by backend only after attempt submission. Null during active attempt.';

COMMENT ON COLUMN placement_answers.skill_code IS
    'Inherited from the parent question skill_code. Backend-controlled.';

-- ============================================================
-- Constraint: one answer per question per attempt
-- ============================================================

CREATE UNIQUE INDEX placement_answers_attempt_question_unique_idx
    ON placement_answers (placement_attempt_id, placement_question_id);

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX placement_answers_attempt_id_idx
    ON placement_answers (placement_attempt_id);

CREATE INDEX placement_answers_question_id_idx
    ON placement_answers (placement_question_id);

CREATE INDEX placement_answers_skill_code_idx
    ON placement_answers (skill_code);

CREATE INDEX placement_answers_is_correct_idx
    ON placement_answers (is_correct);