// P19-007 — Machine-readable placement error codes for client-side i18n.
//
// Clients map these codes to localized strings (e.g. Arabic translations).
// The AppError `message` field stays in English for developer debugging only
// and must never be shown to end users.

export enum PlacementErrorCode {
  NO_ACTIVE_TEST = 'NO_ACTIVE_TEST',
  SECTION_NOT_FOUND = 'SECTION_NOT_FOUND',
  ATTEMPT_NOT_FOUND = 'ATTEMPT_NOT_FOUND',
  ATTEMPT_NOT_ACTIVE = 'ATTEMPT_NOT_ACTIVE',
  ATTEMPT_ALREADY_SUBMITTED = 'ATTEMPT_ALREADY_SUBMITTED',
  ATTEMPT_NOT_SUBMITTED = 'ATTEMPT_NOT_SUBMITTED',
  ATTEMPT_NOT_COMPLETED = 'ATTEMPT_NOT_COMPLETED',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  DUPLICATE_ANSWER = 'DUPLICATE_ANSWER',
  INVALID_ANSWER_VALUE = 'INVALID_ANSWER_VALUE',
  RESULT_NOT_FOUND = 'RESULT_NOT_FOUND',
  ACTIVE_ATTEMPT_EXISTS = 'ACTIVE_ATTEMPT_EXISTS',
  SUBMISSION_PENDING = 'SUBMISSION_PENDING',
  RETAKE_COOLDOWN_ACTIVE = 'PLACEMENT_RETAKE_NOT_ALLOWED',
}
